# Train the model  
Use this notebook to build and train the classification model.

In [172]:
# install dependencies
# %pip install pandas numpy scikit-learn xgboost

In [173]:
import pandas as pd
import numpy as np
import sqlite3
from contextlib import closing

## Loading data

Load the dataset with features, the signatures from the API and concat those.

In [174]:
# load signatures for each hash
with closing(sqlite3.connect("./malwares.sqlite")) as conn:
    cursor = conn.cursor()
    res = cursor.execute("SELECT sha256, signature FROM malwares;")
    signatures = { row[0]: row[1] for row in res.fetchall() }
    
signatures = pd.DataFrame(signatures.items(), columns=["sha256", "signature"])
signatures.head()

                                              sha256       signature
0  da2e5977867a2f47a9b60eb9ffcd29cb8a20a9dbcf474b...     AveMariaRAT
1  0cc686705e924703425f0da5b74295c22dff9fe7791de5...  RedLineStealer
2  1d1947aec877778274e161f12b3f9a1e2a995cf7a5ab8a...  RaccoonStealer
3  2272345c34a9a89b1bc3803e5904206aa662690621cd6e...      AgentTesla
4  734a7e6be53fcde44ad4ac1c0852a73af1ed8398929ff8...          Gafgyt

In [175]:
# load features
features = pd.read_csv("./malware-features.csv")
features.head()

,sha256,file_type,file_size,compilation_date,machine,number_of_sections,number_of_strings,s_0,s_1,s_2,...,s_1990,s_1991,s_1992,s_1993,s_1994,s_1995,s_1996,s_1997,s_1998,s_1999
0,da2e5977867a2f47a9b60eb9ffcd29cb8a20a9dbcf474b...,executable,172975,1632607007,i386,5,2389,1,0,1,...,0,0,0,0,2,4,0,0,0,0
1,0cc686705e924703425f0da5b74295c22dff9fe7791de5...,executable,292352,1681992870,i386,3,4879,3,4,1,...,4,4,3,3,1,5,0,1,4,2
2,9888b5ae54b96dc09337361087c33f12f8c22a8be3b427...,executable,305720,1676207497,i386,11,3322,2,2,2,...,1,1,0,1,1,3,2,2,1,3
3,2272345c34a9a89b1bc3803e5904206aa662690621cd6e...,executable,576000,3398590328,i386,3,6996,1,4,3,...,5,4,2,3,9,6,1,4,0,3
4,734a7e6be53fcde44ad4ac1c0852a73af1ed8398929ff8...,executable,114825,0,x86_64,15,1537,0,0,1,...,2,0,4,1,1,1,0,1,0,0

In [176]:
# data = pd.concat([features, signatures], axis=1, join="inner")
data = pd.merge(features, signatures, on="sha256")
data.head()

,sha256,file_type,file_size,compilation_date,machine,number_of_sections,number_of_strings,s_0,s_1,s_2,...,s_1991,s_1992,s_1993,s_1994,s_1995,s_1996,s_1997,s_1998,s_1999,signature
0,da2e5977867a2f47a9b60eb9ffcd29cb8a20a9dbcf474b...,executable,172975,1632607007,i386,5,2389,1,0,1,...,0,0,0,2,4,0,0,0,0,AveMariaRAT
1,0cc686705e924703425f0da5b74295c22dff9fe7791de5...,executable,292352,1681992870,i386,3,4879,3,4,1,...,4,3,3,1,5,0,1,4,2,RedLineStealer
2,9888b5ae54b96dc09337361087c33f12f8c22a8be3b427...,executable,305720,1676207497,i386,11,3322,2,2,2,...,1,0,1,1,3,2,2,1,3,None
3,2272345c34a9a89b1bc3803e5904206aa662690621cd6e...,executable,576000,3398590328,i386,3,6996,1,4,3,...,4,2,3,9,6,1,4,0,3,AgentTesla
4,734a7e6be53fcde44ad4ac1c0852a73af1ed8398929ff8...,executable,114825,0,x86_64,15,1537,0,0,1,...,0,4,1,1,1,0,1,0,0,Gafgyt

## Cleaning data

In [177]:
# remove rows with no signature
data = data.replace(to_replace='None', value=np.nan).dropna(axis=0, subset=['signature'])
data.head()

,sha256,file_type,file_size,compilation_date,machine,number_of_sections,number_of_strings,s_0,s_1,s_2,...,s_1991,s_1992,s_1993,s_1994,s_1995,s_1996,s_1997,s_1998,s_1999,signature
0,da2e5977867a2f47a9b60eb9ffcd29cb8a20a9dbcf474b...,executable,172975,1632607007,i386,5,2389,1,0,1,...,0,0,0,2,4,0,0,0,0,AveMariaRAT
1,0cc686705e924703425f0da5b74295c22dff9fe7791de5...,executable,292352,1681992870,i386,3,4879,3,4,1,...,4,3,3,1,5,0,1,4,2,RedLineStealer
3,2272345c34a9a89b1bc3803e5904206aa662690621cd6e...,executable,576000,3398590328,i386,3,6996,1,4,3,...,4,2,3,9,6,1,4,0,3,AgentTesla
4,734a7e6be53fcde44ad4ac1c0852a73af1ed8398929ff8...,executable,114825,0,x86_64,15,1537,0,0,1,...,0,4,1,1,1,0,1,0,0,Gafgyt
5,c37e211564b4d5b3447fd8be8526724a4193ac8d9a99ef...,executable,902656,1681776775,i386,3,11441,1,7,8,...,4,10,4,11,7,6,5,5,4,BluStealer

In [178]:
# remove rows with a single signature occurence
is_multi = data["signature"].value_counts() > 1
data = data[data["signature"].isin(is_multi[is_multi].index)]

In [179]:
# extract the features and the target value
y = data.signature
X = data.drop(["sha256", "signature"], axis=1)

In [180]:
from sklearn.preprocessing import LabelEncoder

# label encode categorical columns
encoders = {col: LabelEncoder() for col in X.columns} 
for col in X.columns:
    if X[col].dtype == "object":
        print(f"Fitting encoder for: {col}")
        X[col] = encoders[col].fit_transform(X[col])
        
# label encode target
y_enc = LabelEncoder()
y = y_enc.fit_transform(y)

Fitting encoder for: file_type
Fitting encoder for: machine

In [181]:
X.head()

,file_type,file_size,compilation_date,machine,number_of_sections,number_of_strings,s_0,s_1,s_2,s_3,...,s_1990,s_1991,s_1992,s_1993,s_1994,s_1995,s_1996,s_1997,s_1998,s_1999
0,1,172975,1632607007,4,5,2389,1,0,1,2,...,0,0,0,0,2,4,0,0,0,0
1,1,292352,1681992870,4,3,4879,3,4,1,0,...,4,4,3,3,1,5,0,1,4,2
3,1,576000,3398590328,4,3,6996,1,4,3,2,...,5,4,2,3,9,6,1,4,0,3
4,1,114825,0,12,15,1537,0,0,1,0,...,2,0,4,1,1,1,0,1,0,0
5,1,902656,1681776775,4,3,11441,1,7,8,7,...,3,4,10,4,11,7,6,5,5,4

In [182]:
print(f"Loaded: {len(list(set(y)))} signatures")
y = pd.DataFrame(y, columns=["signature"])
y.head()

Loaded: 58 signatures

   signature
0          4
1         41
2          1
3         18
4          5

In [183]:
#Â split to train and test sets
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, stratify=y)

## Building model

In [184]:

# build model
import xgboost as xgb

model = xgb.XGBClassifier(objective="multi:softprob", n_estimators=500, early_stopping_rounds=200, learning_rate = 0.1)
model.fit(X_train, y_train, eval_set=[(X_train, y_train), (X_valid, y_valid)], verbose=100)

print("Model ready")

[0]	validation_0-mlogloss:2.90612	validation_1-mlogloss:3.02209
[100]	validation_0-mlogloss:0.04493	validation_1-mlogloss:1.22035
[200]	validation_0-mlogloss:0.03026	validation_1-mlogloss:1.25424
[280]	validation_0-mlogloss:0.02733	validation_1-mlogloss:1.27029
Model ready

## Making a prediction

In [185]:
from extract_features import get_features, Features

In [186]:
def feat_to_dataframe(feat: Features):
    columns = [
        "sha256",
        "file_type",
        "file_size",
        "compilation_date",
        "machine",
        "number_of_sections",
        "number_of_strings",
    ] + [f"s_{k}" for k in range(2000)]
    return pd.DataFrame([feat.to_row()], columns=columns)

def feat_to_vector(feat: Features):
    df = feat_to_dataframe(feat)
    df = df.drop(["sha256"], axis=1)
    
    for col in df.columns:
        if df[col].dtype == "object":
            df[col] = encoders[col].transform(df[col])
        
    return df

In [191]:
# get the path to the sample
path = "./samples/00be49f959c2abfe87a5ff1a1a13041af40aa715b4c2c244e3ebbacd0082933c.elf"

# get its features
features = get_features(path)
vector = feat_to_vector(features)


# predict it's signature
prediction = model.predict_proba(vector)[0]
pred = pd.enumerate()

print(sorted(pred, key=lambda x: x[1], reverse=True))

[(31, 0.99528), (55, 0.00020161772), (27, 0.00019908417), (18, 0.00019898565), (6, 0.00019425088), (34, 0.00015932202), (33, 0.00015176566), (19, 0.00015132414), (7, 0.00014169124), (35, 0.00013808081), (29, 0.00013759299), (51, 0.00012019561), (50, 0.000115864364), (15, 0.00011236816), (22, 0.00010357043), (0, 0.000101723956), (54, 9.0755406e-05), (11, 9.030293e-05), (39, 8.7646295e-05), (8, 8.7254986e-05), (56, 8.69202e-05), (40, 8.596901e-05), (44, 8.1685124e-05), (37, 8.1106125e-05), (9, 7.9693345e-05), (43, 7.847809e-05), (4, 7.692556e-05), (3, 7.604711e-05), (21, 7.455297e-05), (47, 7.221292e-05), (48, 7.099912e-05), (32, 6.7490524e-05), (16, 6.4831824e-05), (57, 6.354707e-05), (49, 6.1895174e-05), (10, 5.9852115e-05), (41, 5.8611797e-05), (45, 5.5915076e-05), (53, 5.4116506e-05), (5, 5.3598465e-05), (20, 5.3374082e-05), (52, 5.15387e-05), (1, 4.8657617e-05), (2, 4.8473972e-05), (46, 4.7886348e-05), (42, 4.7701524e-05), (17, 4.5456858e-05), (28, 4.5037432e-05), (23, 4.105835e-05), (12, 3.747547e-05), (13, 3.7087364e-05), (24, 3.4996567e-05), (25, 3.404123e-05), (38, 3.3920678e-05), (14, 3.340555e-05), (26, 3.3134682e-05), (30, 3.2747e-05), (36, 2.610883e-05)]